// ============================================================
// GET /api/articles/{id}/pdf
// ============================================================
// Proxies the PDF report download from Copyleaks.
// The PDF is generated by Copyleaks and stored for ~20 days (expiration: 480h).

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { downloadPdfReport } from '@/lib/copyleaks';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  try {
    const article = await prisma.article.findUnique({
      where: { id },
      include: { scanResult: true },
    });

    if (!article?.scanResult?.copyleaksScanId) {
      return NextResponse.json(
        { error: 'No scan result found for this article' },
        { status: 404 }
      );
    }

    const pdfBuffer = await downloadPdfReport(article.scanResult.copyleaksScanId);

    // Sanitize title for filename
    const safeTitle = (article.title ?? 'report')
      .replace(/[^a-zA-Z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .slice(0, 60);

    return new NextResponse(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="copyleaks-${safeTitle}.pdf"`,
        'Cache-Control': 'private, max-age=3600',
      },
    });
  } catch (error: any) {
    console.error(`[PDF Download] Failed for article ${id}:`, error);
    return NextResponse.json(
      { error: error.message || 'PDF download failed' },
      { status: 500 }
    );
  }
}
